env:
  browser: true
  es2021: true
  jest/globals: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - airbnb
  - 'plugin:jest/recommended'
  - 'plugin:jest/style'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:import/typescript'
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - jest
  - import
  - prettier
rules:
  prettier/prettier: error
  no-use-before-define: off
  '@typescript-eslint/no-use-before-define': error
  react/jsx-filename-extension:
    - 2
    - extensions:
        - '.tsx'
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - '**/*.test.ts?(x)'
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never

globals:
  JSX: true
